### ISSUE TITLE
Speech not working on 2nd host

### ISSUE THREAD

**Issue by Mitchellpkt** [Mitchellpkt/OperatorAware#22]
Cloud speech not working on host machine 
```
(insight) pwn_me_user@PwnMeComputer:~/OperatorAware$ ./start_flask_script_OPEN.sh 
 * Serving Flask app "OperatorAwareFlaskTop.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:2600/ (Press CTRL+C to quit)
70.39.105.4 - - [21/Jun/2018 16:34:10] "GET /index HTTP/1.1" 200 -
Coludn't create upload directory: /home/pwn_me_user/OperatorAware/app/static/
Password accepted
[2018-06-21 16:34:23,470] ERROR in app: Exception on /index [POST]
Traceback (most recent call last):
  File "/home/pwn_me_user/anaconda3/envs/insight/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pwn_me_user/anaconda3/envs/insight/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pwn_me_user/anaconda3/envs/insight/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pwn_me_user/anaconda3/envs/insight/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pwn_me_user/anaconda3/envs/insight/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pwn_me_user/anaconda3/envs/insight/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pwn_me_user/OperatorAware/app/routes.py", line 72, in indexpost
    str_dict_version='newest')
  File "/home/pwn_me_user/OperatorAware/operator_aware_lib/handler_in_str_to_out_str.py", line 55, in handler_in_str_to_out_str
    audio_data, audio_config = load_audio_from_filename(full_audio_file_path)
  File "/home/pwn_me_user/OperatorAware/operator_aware_lib/load_audio_from_filename.py", line 33, in load_audio_from_filename
    from google.cloud.speech import enums
  File "/home/pwn_me_user/.local/lib/python3.6/site-packages/google/cloud/speech/__init__.py", line 26, in <module>
    from google.cloud.speech_v1 import enums
  File "/home/pwn_me_user/.local/lib/python3.6/site-packages/google/cloud/speech_v1/__init__.py", line 17, in <module>
    from google.cloud.speech_v1.gapic import speech_client
  File "/home/pwn_me_user/.local/lib/python3.6/site-packages/google/cloud/speech_v1/gapic/speech_client.py", line 28, in <module>
    from google.cloud.speech_v1.proto import cloud_speech_pb2
  File "/home/pwn_me_user/.local/lib/python3.6/site-packages/google/cloud/speech_v1/proto/cloud_speech_pb2.py", line 30, in <module>
    dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_longrunning_dot_operations__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_rpc_dot_status__pb2.DESCRIPTOR,])
  File "/home/pwn_me_user/.local/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 878, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "google/cloud/speech_v1/proto/cloud_speech.proto":
  google.cloud.speech.v1.RecognizeRequest.config: "google.cloud.speech.v1.RecognizeRequest.config" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognizeRequest.audio: "google.cloud.speech.v1.RecognizeRequest.audio" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognizeRequest: "google.cloud.speech.v1.RecognizeRequest" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.LongRunningRecognizeRequest.config: "google.cloud.speech.v1.LongRunningRecognizeRequest.config" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.LongRunningRecognizeRequest.audio: "google.cloud.speech.v1.LongRunningRecognizeRequest.audio" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.LongRunningRecognizeRequest: "google.cloud.speech.v1.LongRunningRecognizeRequest" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognizeRequest.streaming_request: "google.cloud.speech.v1.StreamingRecognizeRequest.streaming_request" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognizeRequest.streaming_config: "google.cloud.speech.v1.StreamingRecognizeRequest.streaming_config" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognizeRequest.audio_content: "google.cloud.speech.v1.StreamingRecognizeRequest.audio_content" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognizeRequest: "google.cloud.speech.v1.StreamingRecognizeRequest" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognitionConfig.config: "google.cloud.speech.v1.StreamingRecognitionConfig.config" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognitionConfig.single_utterance: "google.cloud.speech.v1.StreamingRecognitionConfig.single_utterance" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognitionConfig.interim_results: "google.cloud.speech.v1.StreamingRecognitionConfig.interim_results" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognitionConfig: "google.cloud.speech.v1.StreamingRecognitionConfig" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig.encoding: "google.cloud.speech.v1.RecognitionConfig.encoding" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig.sample_rate_hertz: "google.cloud.speech.v1.RecognitionConfig.sample_rate_hertz" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig.language_code: "google.cloud.speech.v1.RecognitionConfig.language_code" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig.max_alternatives: "google.cloud.speech.v1.RecognitionConfig.max_alternatives" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig.profanity_filter: "google.cloud.speech.v1.RecognitionConfig.profanity_filter" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig.speech_contexts: "google.cloud.speech.v1.RecognitionConfig.speech_contexts" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig.enable_word_time_offsets: "google.cloud.speech.v1.RecognitionConfig.enable_word_time_offsets" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig.ENCODING_UNSPECIFIED: "google.cloud.speech.v1.RecognitionConfig.ENCODING_UNSPECIFIED" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig.ENCODING_UNSPECIFIED: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "ENCODING_UNSPECIFIED" must be unique within "google.cloud.speech.v1.RecognitionConfig", not just within "AudioEncoding".
  google.cloud.speech.v1.RecognitionConfig.LINEAR16: "google.cloud.speech.v1.RecognitionConfig.LINEAR16" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig.LINEAR16: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "LINEAR16" must be unique within "google.cloud.speech.v1.RecognitionConfig", not just within "AudioEncoding".
  google.cloud.speech.v1.RecognitionConfig.FLAC: "google.cloud.speech.v1.RecognitionConfig.FLAC" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig.FLAC: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "FLAC" must be unique within "google.cloud.speech.v1.RecognitionConfig", not just within "AudioEncoding".
  google.cloud.speech.v1.RecognitionConfig.MULAW: "google.cloud.speech.v1.RecognitionConfig.MULAW" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig.MULAW: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "MULAW" must be unique within "google.cloud.speech.v1.RecognitionConfig", not just within "AudioEncoding".
  google.cloud.speech.v1.RecognitionConfig.AMR: "google.cloud.speech.v1.RecognitionConfig.AMR" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig.AMR: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "AMR" must be unique within "google.cloud.speech.v1.RecognitionConfig", not just within "AudioEncoding".
  google.cloud.speech.v1.RecognitionConfig.AMR_WB: "google.cloud.speech.v1.RecognitionConfig.AMR_WB" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig.AMR_WB: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "AMR_WB" must be unique within "google.cloud.speech.v1.RecognitionConfig", not just within "AudioEncoding".
  google.cloud.speech.v1.RecognitionConfig.OGG_OPUS: "google.cloud.speech.v1.RecognitionConfig.OGG_OPUS" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig.OGG_OPUS: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "OGG_OPUS" must be unique within "google.cloud.speech.v1.RecognitionConfig", not just within "AudioEncoding".
  google.cloud.speech.v1.RecognitionConfig.SPEEX_WITH_HEADER_BYTE: "google.cloud.speech.v1.RecognitionConfig.SPEEX_WITH_HEADER_BYTE" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig.SPEEX_WITH_HEADER_BYTE: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "SPEEX_WITH_HEADER_BYTE" must be unique within "google.cloud.speech.v1.RecognitionConfig", not just within "AudioEncoding".
  google.cloud.speech.v1.RecognitionConfig.AudioEncoding: "google.cloud.speech.v1.RecognitionConfig.AudioEncoding" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionConfig: "google.cloud.speech.v1.RecognitionConfig" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.SpeechContext.phrases: "google.cloud.speech.v1.SpeechContext.phrases" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.SpeechContext: "google.cloud.speech.v1.SpeechContext" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionAudio.audio_source: "google.cloud.speech.v1.RecognitionAudio.audio_source" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionAudio.content: "google.cloud.speech.v1.RecognitionAudio.content" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionAudio.uri: "google.cloud.speech.v1.RecognitionAudio.uri" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognitionAudio: "google.cloud.speech.v1.RecognitionAudio" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognizeResponse.results: "google.cloud.speech.v1.RecognizeResponse.results" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognizeResponse: "google.cloud.speech.v1.RecognizeResponse" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.LongRunningRecognizeResponse.results: "google.cloud.speech.v1.LongRunningRecognizeResponse.results" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.LongRunningRecognizeResponse: "google.cloud.speech.v1.LongRunningRecognizeResponse" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.LongRunningRecognizeMetadata.progress_percent: "google.cloud.speech.v1.LongRunningRecognizeMetadata.progress_percent" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.LongRunningRecognizeMetadata.start_time: "google.cloud.speech.v1.LongRunningRecognizeMetadata.start_time" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.LongRunningRecognizeMetadata.last_update_time: "google.cloud.speech.v1.LongRunningRecognizeMetadata.last_update_time" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.LongRunningRecognizeMetadata: "google.cloud.speech.v1.LongRunningRecognizeMetadata" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognizeResponse.error: "google.cloud.speech.v1.StreamingRecognizeResponse.error" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognizeResponse.results: "google.cloud.speech.v1.StreamingRecognizeResponse.results" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognizeResponse.speech_event_type: "google.cloud.speech.v1.StreamingRecognizeResponse.speech_event_type" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognizeResponse.SPEECH_EVENT_UNSPECIFIED: "google.cloud.speech.v1.StreamingRecognizeResponse.SPEECH_EVENT_UNSPECIFIED" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognizeResponse.SPEECH_EVENT_UNSPECIFIED: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "SPEECH_EVENT_UNSPECIFIED" must be unique within "google.cloud.speech.v1.StreamingRecognizeResponse", not just within "SpeechEventType".
  google.cloud.speech.v1.StreamingRecognizeResponse.END_OF_SINGLE_UTTERANCE: "google.cloud.speech.v1.StreamingRecognizeResponse.END_OF_SINGLE_UTTERANCE" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognizeResponse.END_OF_SINGLE_UTTERANCE: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "END_OF_SINGLE_UTTERANCE" must be unique within "google.cloud.speech.v1.StreamingRecognizeResponse", not just within "SpeechEventType".
  google.cloud.speech.v1.StreamingRecognizeResponse.SpeechEventType: "google.cloud.speech.v1.StreamingRecognizeResponse.SpeechEventType" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognizeResponse: "google.cloud.speech.v1.StreamingRecognizeResponse" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognitionResult.alternatives: "google.cloud.speech.v1.StreamingRecognitionResult.alternatives" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognitionResult.is_final: "google.cloud.speech.v1.StreamingRecognitionResult.is_final" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognitionResult.stability: "google.cloud.speech.v1.StreamingRecognitionResult.stability" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.StreamingRecognitionResult: "google.cloud.speech.v1.StreamingRecognitionResult" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.SpeechRecognitionResult.alternatives: "google.cloud.speech.v1.SpeechRecognitionResult.alternatives" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.SpeechRecognitionResult: "google.cloud.speech.v1.SpeechRecognitionResult" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.SpeechRecognitionAlternative.transcript: "google.cloud.speech.v1.SpeechRecognitionAlternative.transcript" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.SpeechRecognitionAlternative.confidence: "google.cloud.speech.v1.SpeechRecognitionAlternative.confidence" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.SpeechRecognitionAlternative.words: "google.cloud.speech.v1.SpeechRecognitionAlternative.words" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.SpeechRecognitionAlternative: "google.cloud.speech.v1.SpeechRecognitionAlternative" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.WordInfo.start_time: "google.cloud.speech.v1.WordInfo.start_time" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.WordInfo.end_time: "google.cloud.speech.v1.WordInfo.end_time" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.WordInfo.word: "google.cloud.speech.v1.WordInfo.word" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.WordInfo: "google.cloud.speech.v1.WordInfo" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.Speech.Recognize: "google.cloud.speech.v1.Speech.Recognize" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.Speech.LongRunningRecognize: "google.cloud.speech.v1.Speech.LongRunningRecognize" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.Speech.StreamingRecognize: "google.cloud.speech.v1.Speech.StreamingRecognize" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.Speech: "google.cloud.speech.v1.Speech" is already defined in file "google/cloud/proto/speech/v1/cloud_speech.proto".
  google.cloud.speech.v1.RecognizeRequest.config: "google.cloud.speech.v1.RecognitionConfig" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.RecognizeRequest.audio: "google.cloud.speech.v1.RecognitionAudio" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.LongRunningRecognizeRequest.config: "google.cloud.speech.v1.RecognitionConfig" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.LongRunningRecognizeRequest.audio: "google.cloud.speech.v1.RecognitionAudio" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.StreamingRecognizeRequest.streaming_config: "google.cloud.speech.v1.StreamingRecognitionConfig" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.StreamingRecognitionConfig.config: "google.cloud.speech.v1.RecognitionConfig" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.RecognitionConfig.encoding: "google.cloud.speech.v1.RecognitionConfig.AudioEncoding" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.RecognitionConfig.speech_contexts: "google.cloud.speech.v1.SpeechContext" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.RecognizeResponse.results: "google.cloud.speech.v1.SpeechRecognitionResult" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.LongRunningRecognizeResponse.results: "google.cloud.speech.v1.SpeechRecognitionResult" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.StreamingRecognizeResponse.results: "google.cloud.speech.v1.StreamingRecognitionResult" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.StreamingRecognizeResponse.speech_event_type: "google.cloud.speech.v1.StreamingRecognizeResponse.SpeechEventType" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.StreamingRecognitionResult.alternatives: "google.cloud.speech.v1.SpeechRecognitionAlternative" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.SpeechRecognitionResult.alternatives: "google.cloud.speech.v1.SpeechRecognitionAlternative" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.SpeechRecognitionAlternative.words: "google.cloud.speech.v1.WordInfo" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.Speech.Recognize: "google.cloud.speech.v1.RecognizeRequest" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.Speech.Recognize: "google.cloud.speech.v1.RecognizeResponse" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.Speech.LongRunningRecognize: "google.cloud.speech.v1.LongRunningRecognizeRequest" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.Speech.StreamingRecognize: "google.cloud.speech.v1.StreamingRecognizeRequest" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
  google.cloud.speech.v1.Speech.StreamingRecognize: "google.cloud.speech.v1.StreamingRecognizeResponse" seems to be defined in "google/cloud/proto/speech/v1/cloud_speech.proto", which is not imported by "google/cloud/speech_v1/proto/cloud_speech.proto".  To use it here, please add the necessary import.
```

**Comment by Mitchellpkt** [comment]
```
(insight) pwn_me_user@PwnMeComputer:~/OperatorAware$ conda list
# packages in environment at /home/pwn_me_user/anaconda3/envs/insight:
#
# Name                    Version                   Build  Channel
backcall                  0.1.0                    py36_0  
blas                      1.0                         mkl  
bleach                    2.1.3                    py36_0  
ca-certificates           2018.03.07                    0  
certifi                   2018.4.16                py36_0  
click                     6.7              py36h5253387_0  
cycler                    0.10.0           py36h93f1223_0  
dbus                      1.13.2               h714fa37_1  
decorator                 4.3.0                    py36_0  
entrypoints               0.2.3            py36h1aec115_2  
expat                     2.2.5                he0dffb1_0  
flask                     1.0.2                    py36_1  
fontconfig                2.12.6               h49f89f6_0  
freetype                  2.8                  hab7d2ae_1  
glib                      2.56.1               h000015b_0  
gmp                       6.1.2                h6c8ec71_1  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
html5lib                  1.0.1            py36h2f9c1c0_0  
icu                       58.2                 h9c2bf20_1  
intel-openmp              2018.0.3                      0  
ipykernel                 4.8.2                    py36_0  
ipython                   6.4.0                    py36_0  
ipython_genutils          0.2.0            py36hb52b0d5_0  
ipywidgets                7.2.1                    py36_0  
itsdangerous              0.24             py36h93cc618_1  
jedi                      0.12.0                   py36_1  
jinja2                    2.10             py36ha16c418_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0            py36h006f8b5_0  
jupyter                   1.0.0                    py36_4  
jupyter_client            5.2.3                    py36_0  
jupyter_console           5.2.0            py36he59e554_1  
jupyter_core              4.4.0            py36h7c827e3_0  
kiwisolver                1.0.1            py36h764f252_0  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran-ng            7.2.0                hdf63c60_3  
libpng                    1.6.34               hb9fc6fc_0  
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              7.2.0                hdf63c60_3  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                h26e45fe_1  
markupsafe                1.0              py36hd9260cd_1  
matplotlib                2.2.2            py36h0e671d2_1  
mistune                   0.8.3            py36h14c3975_1  
mkl                       2018.0.3                      1  
mkl_fft                   1.0.1            py36h3010b51_0  
mkl_random                1.0.1            py36h629b387_0  
nbconvert                 5.3.1            py36hb41ffb7_0  
nbformat                  4.4.0            py36h31c9010_0  
ncurses                   6.1                  hf484d3e_0  
notebook                  5.5.0                    py36_0  
numpy                     1.14.5           py36hcd700cb_0  
numpy-base                1.14.5           py36hdbf6ddf_0  
openssl                   1.0.2o               h20670df_0  
pandas                    0.23.1           py36h637b7d7_0  
pandoc                    1.19.2.1             hea2e7c5_1  
pandocfilters             1.4.2            py36ha6701b7_1  
parso                     0.2.1                    py36_0  
pcre                      8.42                 h439df22_0  
pexpect                   4.6.0                    py36_0  
pickleshare               0.7.4            py36h63277f8_0  
pip                       10.0.1                   py36_0  
prompt_toolkit            1.0.15           py36h17d85b1_0  
ptyprocess                0.5.2            py36h69acd42_0  
pygments                  2.2.0            py36h0d3125c_0  
pyparsing                 2.2.0            py36hee85983_1  
pyqt                      5.9.2            py36h751905a_0  
python                    3.6.5                hc3d631a_2  
python-dateutil           2.7.3                    py36_0  
pytz                      2018.4                   py36_0  
pyzmq                     17.0.0           py36h14c3975_0  
qt                        5.9.5                h7e424d6_0  
qtconsole                 4.3.1            py36h8f73b5b_0  
readline                  7.0                  ha6073c6_4  
scikit-learn              0.19.1           py36h7aa7ec6_0  
scipy                     1.1.0            py36hfc37229_0  
send2trash                1.5.0                    py36_0  
setuptools                39.2.0                   py36_0  
simplegeneric             0.8.1                    py36_2  
sip                       4.19.8           py36hf484d3e_0  
six                       1.11.0           py36h372c433_1  
sqlite                    3.24.0               h84994c4_0  
terminado                 0.8.1                    py36_1  
testpath                  0.3.1            py36h8cadb63_0  
tk                        8.6.7                hc745277_3  
tornado                   5.0.2                    py36_0  
traitlets                 4.3.2            py36h674d592_0  
wcwidth                   0.1.7            py36hdf4376a_0  
webencodings              0.5.1            py36h800622e_1  
werkzeug                  0.14.1                   py36_0  
wheel                     0.31.1                   py36_0  
widgetsnbextension        3.2.1                    py36_0  
xz                        5.2.4                h14c3975_4  
zeromq                    4.2.5                h439df22_0  
zlib                      1.2.11               ha838bed_2  
```

**Comment by Mitchellpkt** [comment]
Fixed.

When installing everything, ONLY use: `pip3 install --upgrade google-cloud-speech`
