### ISSUE TITLE
Slice up audio files

### ISSUE THREAD

**Issue by Mitchellpkt** [Mitchellpkt/OperatorAware#24]
Send through each < 1 min & concatenate results to avoid API limits

**Comment by Mitchellpkt** [comment]
https://github.com/jiaaro/pydub/

**Comment by Mitchellpkt** [comment]
Implemented in `chop_up_audio`

looks great, except ... its outputs aren't compatible with `transcribe_audio_cloud`

```
[<FileStorage: 'murder_long.mp3' ('audio/mpeg')>]
<FileStorage: 'murder_long.mp3' ('audio/mpeg')>
murder_long.mp3 is the filename
Accepted incoming file:  murder_long.mp3
Saved it to:  /home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/app/static//murder_long.mp3
Converting from mp3
/home/m/anaconda3/lib/python3.6/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
[2018-06-22 21:16:16,013] ERROR in app: Exception on /index [POST]
Traceback (most recent call last):
  File "/home/m/anaconda3/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 54, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/m/anaconda3/lib/python3.6/site-packages/grpc/_channel.py", line 500, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/m/anaconda3/lib/python3.6/site-packages/grpc/_channel.py", line 434, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Invalid recognition 'config': bad sample rate hertz.)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/m/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/app/routes.py", line 61, in indexpost
    transcription_directory_path='auto', qVerbose=1, str_dict_version='newest')
  File "/home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/operator_aware_lib/handler_in_str_to_out_str.py", line 85, in handler_in_str_to_out_str
    transcription_str = fetch_transcript(audio_data, audio_config, use_transcript_directory, qVerbose=qVerbose, force_fresh=0, do_not_save=0)
  File "/home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/operator_aware_lib/fetch_transcript.py", line 56, in fetch_transcript
    transcription_str, response = transcribe_audio_cloud(audio_data, audio_config)
  File "/home/m/Dropbox/Projects/OperatorAware/GitPath/operatoraware/operator_aware_lib/transcribe_audio_cloud.py", line 43, in transcribe_audio_cloud
    response = client.recognize(audio_config, audio_data)
  File "/home/m/anaconda3/lib/python3.6/site-packages/google/cloud/speech_v1/gapic/speech_client.py", line 191, in recognize
    request, retry=retry, timeout=timeout, metadata=metadata)
  File "/home/m/anaconda3/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 139, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/m/anaconda3/lib/python3.6/site-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "/home/m/anaconda3/lib/python3.6/site-packages/google/api_core/retry.py", line 177, in retry_target
    return target()
  File "/home/m/anaconda3/lib/python3.6/site-packages/google/api_core/timeout.py", line 206, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/m/anaconda3/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 56, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 Invalid recognition 'config': bad sample rate hertz.


```

**Comment by Mitchellpkt** [comment]
Added line to the module for loading the audio and manually specified 8000 Hz. ** Need to add in a line to check that this is the case for future files ** (open an issue?)

**Comment by Mitchellpkt** [comment]
Transcriptions need to be indexed, not overwriting each other with each segment.

Just add +.str(index) to the filename?

**Comment by Mitchellpkt** [comment]
Got it, works for 6-minute mp3...!
