### ISSUE TITLE
Bug in comparison

### ISSUE THREAD

**Issue by Mitchellpkt** [Mitchellpkt/OperatorAware#39]
```
11anabellavara.flac.3
***************************
Fresh transcription stored in: /home/pwn_me_user/operatoraware/CACHE_transcriptions/e2b728e9db39e186bd31680a194d3e74c2dbc26340200d904cb00372b8f146e7.txt
Transcription:

Transcription for segment:

Danger words:
{'weaponWords': ['knife', 'gun', 'guns', 'weapon', 'weapons', 'shoot', 'shot', 'armed', 'shotgun', 'handgun', 'rifle', 'bullet'], 'medicalWords': ['heart', 'stroke', 'breathing', 'unconscious', 'collapsed', 'diabetic', 'ambulance', 'doctor', 'hospital', 'blood', 'CPR'], 'vehicleWords': ['crash', 'accident', 'airbag'], 'domesticWords': ['domestic', 'abuse', 'fight', 'argument', 'arguing', 'relationship'], 'fireWords': ['fire', 'fires', 'burn', 'burned', 'burning', 'arson', 'flame', 'flames'], 'miscWords': ['violent', 'suicidal', 'suicide', 'drunk', 'trapped', 'missing'], 'drugWords': ['alcohol', 'beer', 'wine', 'liquor', 'drink', 'drinking', 'drunk', 'belligerent', 'marijuana', 'weed', 'pot', 'meth', 'herion', 'crack', 'cocaine'], 'benignWords': ['butt', 'wrong number']}
******************************
Net transcription:
 ///  okay where are you  where  I don't know his coming ///  /// 
[2018-06-27 12:52:00,173] ERROR in app: Exception on /index [POST]
Traceback (most recent call last):
  File "/home/pwn_me_user/anaconda3/envs/insight/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pwn_me_user/anaconda3/envs/insight/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pwn_me_user/anaconda3/envs/insight/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pwn_me_user/anaconda3/envs/insight/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pwn_me_user/anaconda3/envs/insight/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pwn_me_user/anaconda3/envs/insight/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pwn_me_user/operatoraware/app/routes.py", line 69, in indexpost
    min_conf = float(min(confidence_metric))
TypeError: '<' not supported between instances of 'int' and 'str'

```

**Comment by Mitchellpkt** [comment]
fixed
